### ISSUE TITLE
Snapshot can be unavailable for seconds for embedded replica client

### ISSUE THREAD

**Issue by haaawk** [tursodatabase/libsql#1310]
```
Syncing
2024-04-11T19:12:29Z app[48e5369b732e98] iad [info]2024-04-11T19:12:29.416879Z ERROR tower_http::trace::on_failure: response failed classification=Code: 14 latency=10 ms
2024-04-11T19:12:29Z app[48e5369b732e98] iad [info]2024-04-11T19:12:29.417006Z ERROR consumer: Error syncing: Replication(Client(Status { code: Unavailable, message: "snapshot not found", metadata: MetadataMap { headers: {"access-control-allow-credentials": "true", "access-control-allow-origin": "*", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "content-type": "application/grpc-web+proto", "date": "Thu, 11 Apr 2024 19:12:28 GMT", "fly-request-id": "01HV796RPY4984ZQ3RGC4ZMPBR-iad", "via": "2 fly.io, 1.1 fly.io", "content-length": "0", "server": "Fly/e7839a863 (2024-04-09)", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers"} }, source: None }))
2024-04-11T19:12:29Z app[48e5369b732e98] iad [info]2024-04-11T19:12:29.894703Z  INFO consumer: Syncing
2024-04-11T19:12:29Z app[48e5369b732e98] iad [info]2024-04-11T19:12:29.909297Z ERROR tower_http::trace::on_failure: response failed classification=Code: 14 latency=4 ms
2024-04-11T19:12:29Z app[48e5369b732e98] iad [info]2024-04-11T19:12:29.909421Z ERROR consumer: Error syncing: Replication(Client(Status { code: Unavailable, message: "snapshot not found", metadata: MetadataMap { headers: {"access-control-allow-credentials": "true", "access-control-allow-origin": "*", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "content-type": "application/grpc-web+proto", "date": "Thu, 11 Apr 2024 19:12:28 GMT", "fly-request-id": "01HV796S6GX5Y2FTAEJAB66ZT5-iad", "via": "2 fly.io, 1.1 fly.io", "content-length": "0", "server": "Fly/e7839a863 (2024-04-09)", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers"} }, source: None }))
2024-04-11T19:12:31Z app[48e5369b732e98] iad [info]2024-04-11T19:12:31.395192Z  INFO consumer: Syncing
2024-04-11T19:12:31Z app[48e5369b732e98] iad [info]2024-04-11T19:12:31.409973Z ERROR tower_http::trace::on_failure: response failed classification=Code: 14 latency=4 ms
2024-04-11T19:12:31Z app[48e5369b732e98] iad [info]2024-04-11T19:12:31.410083Z ERROR consumer: Error syncing: Replication(Client(Status { code: Unavailable, message: "snapshot not found", metadata: MetadataMap { headers: {"access-control-allow-credentials": "true", "access-control-allow-origin": "*", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "content-type": "application/grpc-web+proto", "date": "Thu, 11 Apr 2024 19:12:30 GMT", "fly-request-id": "01HV796TNDKD48DBBSKXP50Y7J-iad", "via": "2 fly.io, 1.1 fly.io", "content-length": "0", "server": "Fly/e7839a863 (2024-04-09)", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers"} }, source: None }))
2024-04-11T19:12:31Z app[48e5369b732e98] iad [info]2024-04-11T19:12:31.894765Z  INFO consumer: Syncing
2024-04-11T19:12:31Z app[48e5369b732e98] iad [info]2024-04-11T19:12:31.909802Z ERROR tower_http::trace::on_failure: response failed classification=Code: 14 latency=4 ms
2024-04-11T19:12:31Z app[48e5369b732e98] iad [info]2024-04-11T19:12:31.909918Z ERROR consumer: Error syncing: Replication(Client(Status { code: Unavailable, message: "snapshot not found", metadata: MetadataMap { headers: {"access-control-allow-credentials": "true", "access-control-allow-origin": "*", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "content-type": "application/grpc-web+proto", "date": "Thu, 11 Apr 2024 19:12:30 GMT", "fly-request-id": "01HV796V51HGAYGCG4H73YHGZJ-iad", "via": "2 fly.io, 1.1 fly.io", "content-length": "0", "server": "Fly/e7839a863 (2024-04-09)", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers"} }, source: None }))
```

**Comment by Tehnix** [comment]
Also experiencing this via the JS/Node client:

```
2024-12-25T22:02:33.423654Z ERROR tower_http::trace::on_failure: response failed classification=Code: 14 latency=44 ms
Error: 291 |    * Executes the SQL statement and returns an info object.
292 |    */
293 |   run(...bindParameters) {
294 |     try {
295 |       if (bindParameters.length == 1 && typeof bindParameters[0] === "object") {
296 |         return statementRun.call(this.stmt, bindParameters[0]);
                                  ^
error: Replication(Client(Status { code: Unavailable, message: "snapshot not found", metadata: MetadataMap { headers: {"access-control-allow-credentials": "true", "access-control-allow-origin": "*", "access-control-expose-headers": "grpc-status,grpc-message,grpc-status-details-bin", "content-type": "application/grpc-web+proto", "date": "Wed, 25 Dec 2024 22:02:32 GMT", "fly-request-id": "01JFZXFKJ87RP4JEQ9V10VD07Y-fra", "via": "2 fly.io, 1.1 fly.io", "content-length": "0", "server": "Fly/d5165e6e2 (2024-12-18)", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers"} }, source: None }))
      at run ($HOME/project/node_modules/libsql/index.js:296:29)
      at executeStmt ($HOME/project/node_modules/@libsql/client/lib-esm/sqlite3.js:270:34)
      at execute ($HOME/project/node_modules/@libsql/client/lib-esm/sqlite3.js:67:19)
      at $HOME/project/node_modules/@libsql/kysely-libsql/lib-esm/index.js:70:37
      at executeQuery ($HOME/project/node_modules/@libsql/kysely-libsql/lib-esm/index.js:68:24)
      at $HOME/project/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:45
      at $HOME/project/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:52
      at $HOME/project/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:26
```

I am executing statements quite rapidly, don't know if that might affect it?
