### ISSUE TITLE
libsql returning 502 on prod

### ISSUE THREAD

**Issue by esau-morais** [tursodatabase/libsql#1341]
```
LibsqlError: SERVER_ERROR: Server returned HTTP status 502
at mapHranaError (/var/task/node_modules/@libsql/client/lib-cjs/hrana.js:287:16)
at HttpClient.execute (/var/task/node_modules/@libsql/client/lib-cjs/http.js:87:48)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async m (/var/task/.next/server/chunks/651.js:6:3058)
at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
at async rP (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
at async r5 (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1139)
at async ei (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:26320)
at async es.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1026)
at async r3.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:508) {
code: 'SERVER_ERROR',
rawCode: undefined,
digest: '1139740358',
[cause]: HttpServerError: Server returned HTTP status 502
at errorFromResponse (/var/task/node_modules/@libsql/hrana-client/lib-cjs/http/stream.js:367:12)
at /var/task/node_modules/@libsql/hrana-client/lib-cjs/http/stream.js:256:24
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
status: 502
}
}
```

suddenly it started returning an 502 error, but I couldn't reproduce locally, only in prod

[link to repo](https://github.com/esau-morais/theprimequest)

**Comment by esau-morais** [comment]
i was trying to use zod's `asyncSafeParse` in a schema that didn't manage async functions mb
