### ISSUE TITLE
libsql will not build on windows

### ISSUE THREAD

**Issue by gregtbrown** [tursodatabase/libsql#1849]
the code at: https://github.com/tursodatabase/libsql/blob/main/libsql-ffi/build.rs#L42

should be (based on the build platform) something like:
```
 Command::new("xcopy")
     .arg("/S")
     .arg(format!("{dir}\\{bindgen_rs_path}"))
     .arg(&out_path)
     .output()
     .unwrap();
```
I hacked this into the files installed by `cargo add libsql` and it allowed it to build and run successfully.

**Comment by yuyang-ok** [comment]
~~~
2025-03-14T09:50:23.5807721+08:00 ERROR FetchBuildDataError: error: failed to run custom build command for `libsql-ffi v0.5.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `D:\db\target\debug\build\libsql-ffi-80f5b92615d65999\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=bundled/src/sqlite3.c

  --- stderr

  thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\libsql-ffi-0.5.0\build.rs:48:10:
  called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\panicking.rs:692
     1: core::panicking::panic_fmt
               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\panicking.rs:75
     2: core::result::unwrap_failed
               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\result.rs:1704
     3: std::rt::lang_start
     4: std::rt::lang_start
     5: std::rt::lang_start
     6: std::rt::lang_start
     7: std::rt::lang_start_internal::closure$1
~~~

Is this the same issue??? I can build in with `git-bash`.

**Comment by yuyang-ok** [comment]
noone cares this???
