### ISSUE TITLE
Unable to run project getting the following error Error: Cannot find module '@libsql/darwin-x64'

### ISSUE THREAD

**Issue by been-there-done-that** [tursodatabase/libsql#385]
Unable to run the project getting the following error everytime trying to run the project.

nuxt3 + drizzle + turso

```js
No config path provided, using default path
Reading config file '<path>/drizzle.config.ts'
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module '@libsql/darwin-x64'
Require stack:
- <path>/node_modules/.pnpm/libsql@0.1.8/node_modules/libsql/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (<path>/node_modules/.pnpm/libsql@0.1.8/node_modules/libsql/index.js:26:24)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at newLoader (<path>/node_modules/.pnpm/drizzle-kit@0.19.13/node_modules/drizzle-kit/index.cjs:8627:13)
    at Object.newLoader [as .js] (<path>/node_modules/.pnpm/drizzle-kit@0.19.13/node_modules/drizzle-kit/index.cjs:8627:13)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<path>/node_modules/.pnpm/libsql@0.1.8/node_modules/libsql/index.js'
  ]
}

Node.js v20.5.1
```

getting the following while trying to use drizzle + turso.

Previously worked on multiple projects with the same combination this is a new project getting the above error.

Let me know if anything is needed.

**Comment by been-there-done-that** [comment]
# update

downgrading the version to 0.3.4 working as intended.

```
"@libsql/client": "^0.3.4",
```
