### ISSUE TITLE
Invalid kernel address exception on connection close

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql#419]
Reported by Alexey Orlenko:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               node [11985]
Path:                  /Users/USER/*/node
Identifier:            node
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        bash [11983]
Responsible:           alacritty [4397]
User ID:               501

Date/Time:             2023-09-21 22:01:39.6144 +0200
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        D4DFF34E-7566-D35A-7435-D19F652D17E0

Sleep/Wake UUID:       8107A074-4EF4-48D5-B0D3-0E46347C37C4

Time Awake Since Boot: 310000 seconds
Time Since Wake:       25347 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x3d2072656469766f -> 0x000072656469766f (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x3d2072656469766f

VM Region Info: 0x72656469766f is not in any region.  Bytes after previous region: 20226148759152  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END

Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_pthread.dylib       	       0x1932ce558 pthread_mutex_lock + 12
1   index.node                    	       0x119527414 sqlite3Close + 88
2   index.node                    	       0x11931966c core::ptr::drop_in_place$LT$libsql..v1..connection..Connection$GT$::h716160709af6f4d1 + 76
3   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
4   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
5   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
6   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
7   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
8   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
9   index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
10  index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
11  index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
12  index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
13  index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
14  index.node                    	       0x119318d70 core::ptr::drop_in_place$LT$libsql..v2..rows..LibsqlRows$GT$::h0a37d749b669f69d + 20
```

**Comment by penberg** [comment]
```#0  0x000000000455e240 in ?? ()
#1  0x00007f08a28867c0 in sqlite3Close.part.807 ()
   from /home/aqrln/prisma/prisma-engines/query-engine/driver-adapters/js/node_modules/.pnpm/@libsql+linux-x64-gnu@0.1.16/node_modules/@libsql/linux-x64-gnu/index.node
#2  0x00007f08a2550588 in core::ptr::drop_in_place<libsql::v1::statement::Statement>::h064d8b9ceddfa603 ()
   from /home/aqrln/prisma/prisma-engines/query-engine/driver-adapters/js/node_modules/.pnpm/@libsql+linux-x64-gnu@0.1.16/node_modules/@libsql/linux-x64-gnu/index.node
#3  0x00007f08a255016c in core::ptr::drop_in_place<libsql::v2::rows::LibsqlRows>::h83bc508bf9df8830 ()
   from /home/aqrln/prisma/prisma-engines/query-engine/driver-adapters/js/node_modules/.pnpm/@libsql+linux-x64-gnu@0.1.16/node_modules/@libsql/linux-x64-gnu/index.node
#4  0x00007f08a252944e in neon::types_impl::boxed::JsBox<T>::new::finalizer::hc83eb0b4a674d1bb ()
   from /home/aqrln/prisma/prisma-engines/query-engine/driver-adapters/js/node_modules/.pnpm/@libsql+linux-x64-gnu@0.1.16/node_modules/@libsql/linux-x64-gnu/index.node
#5  0x00007f08a25188e3 in neon::sys::external::finalize_external::h8f18cf80f020af13 ()
   from /home/aqrln/prisma/prisma-engines/query-engine/driver-adapters/js/node_modules/.pnpm/@libsql+linux-x64-gnu@0.1.16/node_modules/@libsql/linux-x64-gnu/index.node
#6  0x0000000000b9543e in void node_napi_env__::CallFinalizer<true>(void (*)(napi_env__*, void*, void*), void*, void*) ()
#7  0x0000000000b7032f in v8impl::RefBase::Finalize() ()
#8  0x0000000000b8f777 in node_napi_env__::DrainFinalizerQueue() ()
#9  0x0000000000b48b68 in node::Environment::RunAndClearNativeImmediates(bool) ()
#10 0x0000000000b49412 in node::Environment::CheckImmediate(uv_check_s*) ()
#11 0x00007f08ccf14ed1 in uv__run_check (loop=loop@entry=0x7f08ccf2f260 <default_loop_struct>) at src/unix/loop-watcher.c:67
#12 0x00007f08ccf0e1c3 in uv_run (loop=0x7f08ccf2f260 <default_loop_struct>, mode=UV_RUN_DEFAULT) at src/unix/core.c:461
#13 0x0000000000ae5f0b in node::SpinEventLoopInternal(node::Environment*) ()
#14 0x0000000000c24628 in node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) ()
#15 0x0000000000c249ea in node::NodeMainInstance::Run() ()
#16 0x0000000000b8c142 in node::Start(int, char**) ()
#17 0x00007f08c9c3dace in __libc_start_call_main (main=main@entry=0xada560 <main>, argc=argc@entry=2, argv=argv@entry=0x7ffd93fdfef8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#18 0x00007f08c9c3db89 in __libc_start_main_impl (main=0xada560 <main>, argc=2, argv=0x7ffd93fdfef8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffd93fdfee8) at ../csu/libc-start.c:360
#19 0x0000000000ae2c15 in _start ()
```
