### ISSUE TITLE
Snapshotting abort failure

### ISSUE THREAD

**Issue by LucioFranco** [tursodatabase/libsql#647]
### Error

```
thread 'tokio-runtime-worker' panicked at libsql-server/src/replication/snapshot.rs:360:13:
assertion failed: frame.header().frame_no < self.last_seen_frame_no
stack backtrace:
   0:     0x56498d092a8c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56498d092a8c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56498d092a8c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56498d092a8c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56498d0c2fcc - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x56498d0c2fcc - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x56498d08ea2e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x56498d092874 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56498d092874 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56498d094063 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x56498d093d7c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x56498d0945e9 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x56498d0944a1 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:     0x56498d092fb6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56498d094232 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x56498be631e3 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x56498be63273 - core::panicking::panic::hd907d42d09324a32
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
  17:     0x56498c49e6d5 - sqld::replication::snapshot::LogCompactor::new::{{closure}}::hc9e663118fcb971e
  18:     0x56498c3fe79f - tokio::runtime::task::raw::poll::h8492560a7f706e9d
  19:     0x56498cff4fe6 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h6100caaa0d9ab38e
  20:     0x56498cff3949 - tokio::runtime::scheduler::multi_thread::worker::run::hf43b69d66875b8f1
  21:     0x56498d003061 - tokio::runtime::task::raw::poll::hcaec217a827ae413
  22:     0x56498cfdd2de - std::sys_common::backtrace::__rust_begin_short_backtrace::h3b521abe8cda4ece
  23:     0x56498cfde4da - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha310c6691172f268
  24:     0x56498d09a7a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haadd4e5af2ab0d62
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  25:     0x56498d09a7a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4ba1fb09c16d807
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  26:     0x56498d09a7a5 - std::sys::unix::thread::Thread::new::thread_start::he524ecf4b47bee95
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f7eb0895dd4 - start_thread
  28:     0x7f7eb09179b0 - __clone3
  29:                0x0 - <unknown>
2023-11-17T20:47:42.271354Z ERROR sqld::replication::primary::logger: fatal error: failed to compact log: log compactor thread exited, exiting
```

### Reproduction

```
minio server /tmp/minio
source .env
RUST_BACKTRACE=full cargo run --release -p sqld -- --enable-namespaces --admin-listen-addr 127.0.0.1:8081 --enable-bottomless-replication --max-log-size 1
```
then run

```
git clone git@github.com:LucioFranco/sqld-stresstest
cargo run -- single-conn
```

**Comment by LucioFranco** [comment]
oh and to get the panic message you need to also run this code https://github.com/tursodatabase/libsql/pull/648
