### ISSUE TITLE
`INSERT INTO` with `RETURNING` statement failure with embedded replica

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql#831]
A `INSERT INTO` with `RETURNING`
```
  const insertSession = await libsqlClient.execute({
    sql: "INSERT INTO Session VALUES(?, ?, ?, ?) RETURNING id as id;",
    args: [
      cuid2.createId(),
      getSessionExpirationDate().toISOString(),
      user?.id || "",
      wallet?.id || "",
...
    ],
  });
```

results the following error:

```
Error: bincode: `Bincode does not support the serde::Deserializer::deserialize_any method`
    at Object.next (/Users/madhava/Sites/guminc/splinter-core/node_modules/libsql/index.js:285:30)
    at Statement.all (/Users/madhava/Sites/guminc/splinter-core/node_modules/libsql/index.js:305:16)
    at executeStmt (file:///Users/madhava/Sites/guminc/splinter-core/node_modules/@libsql/client/lib-esm/sqlite3.js:204:34)
    at Sqlite3Client.execute (file:///Users/madhava/Sites/guminc/splinter-core/node_modules/@libsql/client/lib-esm/sqlite3.js:59:16)
```

Related to issue https://github.com/tursodatabase/libsql/issues/812 probably.

**Comment by coindegen** [comment]
This example in the docs is failing with the same error (https://github.com/tursodatabase/libsql/blob/main/libsql/examples/replica.rs#L40):

```
rust/target/release/upload
Database /var/folders/bx/h4_6kft90lg650mq6jp5hnh40000gn/T/.tmpXIrAx9
2023-12-27T21:07:14.848742Z  INFO libsql_replication::replicator: Attempting to perform handshake with primary.
2023-12-27T21:07:14.848765Z  INFO libsql::replication::remote_client: Attempting to perform handshake with primary.
2023-12-27T21:07:15.202288Z  INFO libsql_replication::replicator: Attempting to perform handshake with primary.
2023-12-27T21:07:15.202327Z  INFO libsql::replication::remote_client: Attempting to perform handshake with primary.
inital sync complete, frame no: Some(10052)
2023-12-27T21:07:15.592668Z  INFO libsql_replication::replicator: Attempting to perform handshake with primary.
2023-12-27T21:07:15.592682Z  INFO libsql::replication::remote_client: Attempting to perform handshake with primary.
2023-12-27T21:07:15.807933Z  INFO libsql_replication::replicator: Attempting to perform handshake with primary.
2023-12-27T21:07:15.807998Z  INFO libsql::replication::remote_client: Attempting to perform handshake with primary.
Rows insert call
thread 'tokio-runtime-worker' panicked at src/main.rs:52:43:
called `Result::unwrap()` on an `Err` value: Bincode(DeserializeAnyNotSupported)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:76:19:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(49), ...)
```
